version: '3.8'

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    image: energy-outsourcing-springboot
    container_name: springboot
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/energy_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: energy_db
      MYSQL_USER: username
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
