version: '3.8'

services:
#  springboot:
##    volumes:
##      - ./logs:/logs
##    build:
##      context: .
##      dockerfile: Dockerfile
##    image: energy-outsourcing-springboot
##    container_name: springboot
##    restart: always
##    environment:
##      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/energy_db?serverTimezone=Asia/Seoul
##      - SPRING_DATASOURCE_USERNAME=username
##      - SPRING_DATASOURCE_PASSWORD=12345
##    ports:
##      - "8080:8080"
##    depends_on:
##      - mysql
##    networks:
##      - energy-network

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: energy_db
      MYSQL_USER: username
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - energy-network

#  weather-fetcher:
#    build:
#      context: .
#      dockerfile: Dockerfile-python
#    container_name: weather-fetcher
#    depends_on:
#      - mysql
#    networks:
#      - energy-network

networks:
  energy-network:
    driver: bridge

volumes:
  mysql_data:
