spring:
  datasource:
    url: jdbc:mysql://mysql:3306/energy_db?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
logging:
  file:
    name: /logs/application.log
  level:
    root: INFO
