spring:
  datasource:
    url: jdbc:mysql://mysql:3306/energy_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  mysql:
    host: mysql
    port: 3306
    database: energy_db
    username: username
    password: 12345
