spring:
  datasource:
    url: jdbc:mysql://localhost:3306/energy_db?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  file:
    name: /logs/application.log
  level:
    root: INFO

rems:
  serialPort: /dev/ttyUSB0
  baudRate: 9600
  dataBits: 8
  stopBits: 1
  parity: NONE

modbus:
  serialPort: /dev/ttyUSB0  # Windows 환경에서는 "COM3" 등으로 설정
  baudRate: 9600
  dataBits: 8
  parity: 0        # 0: NO_PARITY, 1: ODD_PARITY, 2: EVEN_PARITY 등
  stopBits: 1      # 1: ONE_STOP_BIT, 2: TWO_STOP_BITS 등

scheduler:
  profile: test